extraction:
  cpp:
    after_prepare: 
      - python report.py 93
  cobol:
    after_prepare: 
      - python report.py 93
  csharp:
    after_prepare: 
      - python report.py 93
  java:
    after_prepare: 
      - python report.py 93
  javascript:
    after_prepare: 
      - python report.py 93
  python:
    after_prepare: 
      - python report.py 93
